### ISSUE TITLE
AttributeError: module 'moses' has no attribute 'get_all_metrics'

### ISSUE THREAD

**Issue by MorganRO8** [eyalmazuz/MolGen#3]
I'm testing this right now, but I was getting an attribute error:
Traceback (most recent call last):
  File "main.py", line 226, in <module>
    main()
  File "main.py", line 218, in main
    get_stats(train_set=dataset,
  File ".../src/train/evaluate.py", line 444, in get_stats
    metrics = moses.get_all_metrics(generated_smiles)
AttributeError: module 'moses' has no attribute 'get_all_metrics'

I did some digging and it looks like sacremoses is an entirely different thing, and what you meant to include in the environment.yml was molsets, which is also imported as 'moses'.

**Comment by MorganRO8** [comment]
Okay, sacremoses is required, but it is still causing the import in evaluate.py to pull the wrong code.

**Comment by MorganRO8** [comment]
Still confused, in the environment.yml it references molsets 1.0, which does not exist.

**Comment by MorganRO8** [comment]
Figured it out, you need to build molsets from the source, as the version you get from their github is 1.0, the pypi versions are too old apparently.
